import os
import json
import threading
from typing import Any
from reins.services.logger import get_logger
from reins.harness import external_io

logger = get_logger("vault_manager")

class VaultManager:
    """
    Manages the External Memory stored in the Obsidian Vault.
    Maintains the human-readable Markdown 'Wiki' while preserving the 
    XML structure for machine ingestion in the background.
    """
    def __init__(self, mqtt_client: Any) -> None:
        self.mqtt = mqtt_client
        self.wiki_dir = os.path.expanduser("~/data_rein/data-oby/Wiki/Memories")
        
        os.makedirs(self.wiki_dir, exist_ok=True)
        
        _ = external_io.mqtt_subscribe(self.mqtt, "data_rein/vault/save")
        self.mqtt.message_callback_add("data_rein/vault/save", self.on_save_memory)
        logger.info("Vault Manager online. Ready to forge Wiki documentations.")

    def on_save_memory(self, client: Any, userdata: Any, msg: Any) -> None:
        try:
            payload = json.loads(msg.payload.decode("utf-8"))
            thread = threading.Thread(
                target=self._save_memory,
                args=(payload,),
                daemon=True
            )
            thread.start()
        except Exception as e:
            logger.error(f"Failed to process vault save request: {e}")

    def _save_memory(self, payload: dict[str, Any]) -> None:
        title = payload.get("title", "Untitled_Memory").replace(" ", "_")
        content = payload.get("content", "")
        
        if not content:
            logger.warning("Empty memory payload received. Ignoring.")
            return

        # Format as a Wiki documentation (Markdown)
        md_content = f"# {title}\n\n{content}\n\n---\n*Auto-generated by Data Rein Vault Manager*"
        filepath = os.path.join(self.wiki_dir, f"{title}.md")
        
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(md_content)
            logger.info(f"External memory saved to Wiki: {filepath}")
        except Exception as e:
            logger.error(f"Failed to write memory to vault: {e}")

        # Mirror into the single monolith Wiki DB (source of truth for all envs).
        # Graceful degradation: a failure here must never break the vault write.
        try:
            from reins.harness.wiki import WikiDB
            with WikiDB() as db:
                db.upsert_page(
                    title=payload.get("title", "Untitled_Memory"),
                    content=content,
                    source_path=filepath,
                    category="vault",
                    owner="vault_manager",
                )
        except Exception as e:
            logger.error(f"Failed to mirror memory into monolith wiki: {e}")
