import os
import json
import threading
from pathlib import PurePosixPath, PureWindowsPath
from typing import Any
from reins.services.logger import get_logger
from reins.harness import external_io

logger = get_logger("vault_manager")


def sanitize_vault_title(title: str) -> str:
    """Return a filesystem-safe basename for a Vault memory title.

    Memory titles arrive from MQTT payloads (untrusted). A title must never
    escape the fixed wiki directory, so we strip any path components (POSIX
    and Windows separators), drop NUL / dot-only traversal tokens, and render
    it as a bare basename (CWE-22).
    """
    if not isinstance(title, str):
        title = str(title)
    if "\x00" in title:
        raise ValueError("vault title must not contain a NUL byte")

    # Normalise both path flavours to a bare basename (no directory escape).
    for cls in (PureWindowsPath, PurePosixPath):
        if "\\" in title or "/" in title:
            try:
                title = cls(title).name
                break
            except ValueError:
                continue
    # Belt-and-braces: drop any remaining separators / traversal tokens.
    for sep in ("\\", "/"):
        title = title.rsplit(sep, 1)[-1]
    if title in {".", ".."}:
        title = ""
    return title.strip().replace(" ", "_")

class VaultManager:
    """
    Manages the External Memory stored in the Obsidian Vault.
    Maintains the human-readable Markdown 'Wiki' while preserving the 
    XML structure for machine ingestion in the background.
    """
    def __init__(self, mqtt_client: Any) -> None:
        self.mqtt = mqtt_client
        self.wiki_dir = os.path.expanduser("~/data_rein/data-oby/Wiki/Memories")
        
        os.makedirs(self.wiki_dir, exist_ok=True)
        
        _ = external_io.mqtt_subscribe(self.mqtt, "data_rein/vault/save")
        self.mqtt.message_callback_add("data_rein/vault/save", self.on_save_memory)
        logger.info("Vault Manager online. Ready to forge Wiki documentations.")

    def on_save_memory(self, client: Any, userdata: Any, msg: Any) -> None:
        try:
            payload = json.loads(msg.payload.decode("utf-8"))
            thread = threading.Thread(
                target=self._save_memory,
                args=(payload,),
                daemon=True
            )
            thread.start()
        except Exception as e:
            logger.error(f"Failed to process vault save request: {e}")

    def _save_memory(self, payload: dict[str, Any]) -> None:
        title = sanitize_vault_title(payload.get("title", "Untitled_Memory") or "Untitled_Memory")
        content = payload.get("content", "")

        if not content:
            logger.warning("Empty memory payload received. Ignoring.")
            return

        if not title:
            logger.warning("Vault memory title resolved to an empty basename. Ignoring.")
            return

        # Format as a Wiki documentation (Markdown)
        md_content = f"# {title}\n\n{content}\n\n---\n*Auto-generated by Data Rein Vault Manager*"
        # Guard: double-check the resolved file stays inside the wiki directory.
        safe_name = os.path.basename(title)
        filepath = os.path.join(self.wiki_dir, f"{safe_name}.md")
        if os.path.dirname(filepath) != self.wiki_dir.rstrip(os.sep) and not filepath.startswith(self.wiki_dir + os.sep):
            logger.warning("Vault memory path resolved outside wiki dir; ignoring.")
            return

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(md_content)
            logger.info(f"External memory saved to Wiki: {filepath}")
        except Exception as e:
            logger.error(f"Failed to write memory to vault: {e}")

        # Mirror into the single monolith Wiki DB (source of truth for all envs).
        # Graceful degradation: a failure here must never break the vault write.
        self._mirror_into_wiki(payload, filepath)

    def _mirror_into_wiki(self, payload: dict[str, Any], filepath: str) -> None:
        try:
            from reins.harness.wiki import WikiDB

            with WikiDB() as db:
                db.upsert_page(
                    title=payload.get("title", "Untitled_Memory"),
                    content=payload.get("content", ""),
                    source_path=filepath,
                    category="vault",
                    owner="vault_manager",
                )
        except Exception as e:
            logger.error(f"Failed to mirror memory into monolith wiki: {e}")
