import os
import json
import pytest

def test_ody_auth_config():
    """Verify the default factory user is deleted and data-ody is the admin"""
    auth_file = os.path.expanduser("~/data_rein/odysseus/data/auth.json")
    assert os.path.exists(auth_file), "Auth file is missing in the new odysseus clone"
    with open(auth_file, "r") as f:
        auth_data = json.load(f)
    users = auth_data.get("users", {})
    assert "data-ody" in users, "Admin user data-ody was not created"
    assert users["data-ody"]["is_admin"] is True, "data-ody is not an admin"
    assert len(users) == 1, "Factory defaults were not deleted"

def test_ody_dockerfile_python_version():
    """Verify Odysseus is building with the correct 3.12-slim python version for stability"""
    dockerfile = os.path.expanduser("~/data_rein/odysseus/Dockerfile")
    assert os.path.exists(dockerfile), "Dockerfile is missing"
    with open(dockerfile, "r") as f:
        content = f.read()
    assert "python:3.12-slim" in content, "Dockerfile is not using the patched python 3.12-slim version"
    assert "python:3.14-slim" not in content, "Dockerfile contains the broken python 3.14 version"

def test_model_registry_populated():
    """Verify the SysProfiler and CookbookEvaluator correctly mapped local models"""
    registry_file = os.path.expanduser("~/data_rein/data-oby/TrainingData/model_registry.json")
    assert os.path.exists(registry_file), "Model registry was not generated by sys_profiler"
    with open(registry_file, "r") as f:
        registry = json.load(f)
    assert "amdy" in registry, "Local node amdy missing from registry"
    assert len(registry["amdy"].get("models", [])) > 0, "No models were detected by sys_profiler"

def test_memory_ingestion():
    """Verify the data_rein harness memories were imported into Odysseus"""
    memory_file = os.path.expanduser("~/data_rein/odysseus/data/memory.json")
    assert os.path.exists(memory_file), "Memory file was not migrated to Odysseus"
    with open(memory_file, "r") as f:
        memories = json.load(f)
    assert len(memories) > 0, "No memories were found"
    assert any("data_rein" in m.get("text", "") or "PON" in m.get("text", "") for m in memories), "Harness specific memories were not found"
